SierraSystems/Oracle-Modernization

src/backend/libs/justin-data-starter/.gitignore, src/backend/libs/justin-data-starter/pom.xml, src/backend/libs/justin-data-starter/src/main/resources/oracle.properties.template
- Add fix to spring connection
=> 42 Connection issues with oracle

src/frontend/src/components/contacts/Contacts.js, src/frontend/src/index.css
=> fix footer style

src/backend/libs/justin-data-starter/src/main/java/com/nttdata/pocdata/ContactsServiceImpl.java
=> Increment the id

src/backend/libs/justin-data-starter/src/main/java/com/nttdata/pocdata/ContactsServiceImpl.java
=> Fix id bug

src/frontend/src/components/add-contact/AddContact.js, src/frontend/src/components/contacts/Contacts.js, src/frontend/src/components/edit-contact/EditContact.js
Add, edit and delete contact functionality and alerts on Frontend!
=> Add, edit and delete contact functionality and alerts on Frontend!

src/frontend/src/components/contacts/Contacts.css, src/frontend/src/components/contacts/Contacts.js, src/frontend/src/components/edit-contact/EditContact.css, src/frontend/src/components/feedback/Feedback.css
- Responsive design :)
- local
=> Responsive design :)

src/backend/management-api/src/main/resources/application.properties
=> Add property to fix stale connection

src/backend/libs/justin-data-starter/src/main/java/com/nttdata/pocdata/InventoriesDao.java, src/backend/libs/justin-data-starter/src/main/java/com/nttdata/pocdata/InventoriesService.java, src/backend/libs/justin-data-starter/src/main/java/com/nttdata/pocdata/InventoriesServiceImpl.java, src/backend/libs/justin-data-starter/src/main/java/com/nttdata/pocdata/hibernate/InventoriesProcedures.java, src/backend/management-api/src/main/java/com/nttdata/managementapi/controller/TestController.java, src/backend/management-api/src/main/resources/application.properties
=> Stored procedure implementation

src/frontend/src/components/contacts/Contacts.css, src/frontend/src/components/contacts/Contacts.js
- Fix table styling
- local dev
=> Fix table styling (both mobile and desktop)

src/backend/management-api/pom.xml
Close #70
- Moving api to Oracle-Modernization
=> 70 Move management api to Oracle Modernization group

src/frontend/.env.example, src/frontend/package.json, src/frontend/src/App.js, src/frontend/src/components/hoc/AuthenticationGuard.js, src/frontend/src/components/home/Home.js, src/frontend/yarn.lock
HOC: Authentication guard with keycloak
=> HOC: Authentication Guard with keycloak

src/oracle/sql/ot_schema.sql
Update script to include missing ot.
=> Add schema to orders

src/frontend/package.json, src/frontend/yarn.lock
- 🤖 Transformers, frontend dependabots in disguise
- dependencies
=> 🤖 Transformers, frontend dependabots in disguise

src/backend/libs/justin-data-starter/pom.xml, src/backend/management-api/pom.xml
- 🤖 Transformers, backend dependabots in disguise
- dependencies
=> 🤖 Transformers, backend dependabots in disguise

README.md
=> Add fe url to readme

src/backend/libs/justin-data-starter/pom.xml
Delete commented out plugin and duplicate
Increment org.codehaus.mojo version and pom cleanup
Increment org.codehaus.mojo version
Remove duplicate plugin
Remove commented out plugin
=> Increment org.codehaus.mojo version

src/frontend/.gitignore
=> add ignore files

src/frontend/package.json, src/frontend/src/components/hoc/AuthenticationGuard.js, src/frontend/yarn.lock
use gov version for keycloak js
=> use latest version for keycloak js

src/backend/management-api/src/main/resources/application.yml
🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆
=> 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 Hikory Dikory Duck

aks/README.md, aks/azure-fqdn.sh, aks/certmanager.sh, aks/cluster-issuer.yaml, aks/create-cluster.sh, aks/ingress.sh, aks/ingress.yml, aks/keycloak/ingress.yaml, aks/keycloak/keycloak.yaml, docker-compose.yml, src/backend/Dockerfile, src/frontend/Dockerfile, src/frontend/README.md, src/frontend/deployment.yml, src/oracle/create-azure.sh, src/oracle/sql/ot_create_user.sql
=> adding stuff

src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/controller/CustomersResource.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/dao/CustomersDao.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/model/api/Customer.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/service/CustomersService.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/service/CustomersServiceImpl.java
Exposing customer table through api
=> Implement customer endpoint

src/backend/quarkus-management-api/src/main/resources/application.properties
Turning keycloak off for dev till we are setup for it
=> Turn keycloak off for now

src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/controller/ManagementApiImpl.java
Add transactional to enpoints 
Fix outbound mapping on update and add
=> Add transactional and mappings

src/backend/quarkus-management-api/pom.xml, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/controller/ManagementApiImpl.java, src/backend/quarkus-management-api/src/main/resources/application.properties
Add some generic info logs
Add access logs
=> Adding logging

src/frontend/src/components/add-contact/AddContact.js, src/frontend/src/components/contacts/Contacts.js, src/frontend/src/components/customers/Customers.js, src/frontend/src/components/edit-contact/EditContact.js, src/frontend/src/index.css
=> Add customer info page

src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/contact/ContactMapper.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/controller/ContactsApiServiceImpl.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/service/ContactsServiceImpl.java
=> add mapping for customers

src/backend/quarkus-management-api/management-api.yaml, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/contact/ContactsApiServiceImpl.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/contact/ContactsRepository.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/contact/ContactsService.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/contact/ContactsServiceImpl.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/controller/CustomersApiServiceImpl.java, src/frontend/src/components/contacts/Contacts.js, src/frontend/src/components/edit-contact/EditContact.js
=> Update api endpoints

keycloak/realm-export.json, src/frontend/src/components/contacts/Contacts.js
- Add button to load more contacts 🎵 
=> ⏺️🎵 🎵  ⏺️ Load More records ⏺️🎵🎵  ⏺️ 

src/frontend/package.json, src/frontend/src/components/add-contact/AddContact.js, src/frontend/src/components/contacts/Contacts.js, src/frontend/src/components/customers/Customers.js, src/frontend/src/components/edit-contact/EditContact.js, src/frontend/src/components/feedback/Feedback.js, src/frontend/src/components/home/Home.js, src/frontend/src/index.css, src/frontend/yarn.lock
Use latest shared-component styling
local
=> Use latest shared-component styling

src/backend/quarkus-management-api/management-api.yaml
=> simplified api

src/backend/pom.xml, src/backend/quarkus-management-api/management-api.yaml, src/backend/quarkus-management-api/pom.xml, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/common/QueryHelpers.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/contact/ContactsServiceImpl.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/order/OrderDto.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/order/OrderRepository.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/order/OrderService.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/order/OrderServiceImpl.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/order/OrdersApiImpl.java
=>  📦 🎁 😄 Hey what's my order status ?  📦 🎁 😄 

src/frontend/package.json, src/frontend/src/App.js, src/frontend/src/components/hoc/AuthenticationGuard.js, src/frontend/src/components/page/contacts/ContactList.js, src/frontend/src/components/page/home/Home.js, src/frontend/yarn.lock
=> ⏪ ◀️ ▶️  ⏩ Where am I going ? ⏪ ◀️ ▶️  ⏩

src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/order/OrderDto.java, src/backend/quarkus-management-api/src/main/java/com/nttdata/quarkus/management/api/order/OrderRepository.java
- set up left join on the query
=> Better queries  left join boy

src/frontend/src/App.js, src/frontend/src/components/hoc/AuthenticationGuard.js, src/frontend/src/components/page/home/Home.js
Login button for auth, homepage unprotected & others protected
Locally
=> Login button for auth, homepage unprotected & others protected

src/frontend/.env.example, src/frontend/package.json, src/frontend/src/App.js, src/frontend/src/components/page/home/Home.js, src/frontend/src/index.css, src/frontend/yarn.lock
Button in header (Login and Logout functionality)
=> Button in header (Login and Logout functionality)
